// Test-only original solutions. Never import this file into application code.
import type { HouseAction } from "../functions/src/shared/decorum";
export const solutionMoves: Record<string, HouseAction[]> = {
  "demo-two-01": [
    { type: "decorPaint", roomId: "living", color: "green" },
    { type: "decorPaint", roomId: "bed", color: "yellow" },
    { type: "decorPaint", roomId: "bath", color: "blue" },
    { type: "decorSwap", roomId: "living", objectId: "lamp-blue-modern" },
    { type: "decorAdd", roomId: "living", objectId: "curio-yellow-antique" },
    { type: "decorAdd", roomId: "bath", objectId: "art-blue-antique" },
    { type: "decorRemove", roomId: "kitchen", objectType: "lamp" },
    { type: "decorAdd", roomId: "kitchen", objectId: "curio-red-unusual" },
    { type: "decorAdd", roomId: "kitchen", objectId: "art-green-retro" },
  ],
  "demo-two-02": [
    { type: "decorPaint", roomId: "living", color: "green" },
    { type: "decorPaint", roomId: "bath", color: "yellow" },
    { type: "decorPaint", roomId: "bed", color: "yellow" },
    { type: "decorPaint", roomId: "kitchen", color: "blue" },
    { type: "decorSwap", roomId: "bath", objectId: "curio-blue-retro" },
    { type: "decorAdd", roomId: "bath", objectId: "lamp-yellow-retro" },
    { type: "decorSwap", roomId: "bed", objectId: "lamp-blue-modern" },
    { type: "decorAdd", roomId: "bed", objectId: "curio-red-unusual" },
    { type: "decorSwap", roomId: "living", objectId: "lamp-blue-modern" },
    { type: "decorAdd", roomId: "living", objectId: "curio-yellow-antique" },
    { type: "decorAdd", roomId: "living", objectId: "art-green-retro" },
    { type: "decorRemove", roomId: "kitchen", objectType: "lamp" },
    { type: "decorAdd", roomId: "kitchen", objectId: "curio-green-modern" },
    { type: "decorAdd", roomId: "kitchen", objectId: "art-blue-antique" },
  ],
  "demo-three-01": [
    { type: "decorPaint", roomId: "living", color: "green" },
    { type: "decorPaint", roomId: "bed", color: "blue" },
    { type: "decorPaint", roomId: "bath", color: "yellow" },
    { type: "decorPaint", roomId: "kitchen", color: "yellow" },
    { type: "decorAdd", roomId: "bath", objectId: "lamp-yellow-retro" },
    { type: "decorAdd", roomId: "bath", objectId: "art-blue-antique" },
    { type: "decorSwap", roomId: "bed", objectId: "lamp-blue-modern" },
    { type: "decorAdd", roomId: "bed", objectId: "curio-red-unusual" },
    { type: "decorAdd", roomId: "bed", objectId: "art-green-retro" },
    { type: "decorSwap", roomId: "living", objectId: "lamp-blue-modern" },
    { type: "decorAdd", roomId: "living", objectId: "curio-yellow-antique" },
    { type: "decorRemove", roomId: "kitchen", objectType: "lamp" },
    { type: "decorAdd", roomId: "kitchen", objectId: "curio-blue-retro" },
    { type: "decorAdd", roomId: "kitchen", objectId: "art-red-modern" },
  ],
  "demo-four-01": [
    { type: "decorPaint", roomId: "living", color: "green" },
    { type: "decorPaint", roomId: "bath", color: "yellow" },
    { type: "decorPaint", roomId: "bed", color: "blue" },
    { type: "decorAdd", roomId: "bath", objectId: "lamp-blue-modern" },
    { type: "decorSwap", roomId: "bath", objectId: "curio-yellow-antique" },
    { type: "decorAdd", roomId: "bath", objectId: "art-green-retro" },
    { type: "decorAdd", roomId: "bed", objectId: "curio-blue-retro" },
    { type: "decorAdd", roomId: "bed", objectId: "art-red-modern" },
    { type: "decorSwap", roomId: "living", objectId: "lamp-blue-modern" },
    { type: "decorAdd", roomId: "living", objectId: "curio-yellow-antique" },
    { type: "decorRemove", roomId: "kitchen", objectType: "lamp" },
    { type: "decorAdd", roomId: "kitchen", objectId: "curio-green-modern" },
    { type: "decorAdd", roomId: "kitchen", objectId: "art-blue-antique" },
  ],
};
